vich_uploader:
    db_driver: orm

    mappings:
        magazines_image:
            uri_prefix: /image/magazines
            upload_destination: '%kernel.project_dir%/public/images/magazines'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
